apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-deploy-githubaction
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: prithvi081099
        # The Github repository
        repo: githubAction
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - deploy
      requeueAfterSeconds: 30
  template:
    metadata:
      name: 'myapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/prithvi081099/argoCD.git
        targetRevision: HEAD
        path: dev/githubAction
        helm:
          parameters:
          - name: "image.tag"
            value: "{{head_sha}}" 
      destination:
        server: https://kubernetes.default.svc
        namespace: 'test-new-{{head_sha}}'
      
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true